import 'bootstrap'
import './assets/scss/style.scss'
import './assets/scss/swiper.scss'
import './assets/scss/custom.scss'
import './assets/scss/tab.scss'
import './assets/scss/gold.scss'
import './assets/scss/shop.scss'

import './assets/js/swiper.js'
import './assets/js/test.js'
import './assets/js/healthbar.js'
import './assets/js/save-game.js'
