import 'bootstrap'
import './assets/scss/style.scss'
import './assets/scss/swiper.scss'
import './assets/scss/custom.scss'
import './assets/scss/tab.scss'
import './assets/scss/gold.scss'
import './assets/scss/shop.scss'
import './assets/scss/stats.scss'
import './assets/scss/sprite-abilities.scss'
import './assets/scss/adaptive.scss'

import './assets/js/swiper.js'
import './assets/js/healthbar.js'
import './assets/js/save-game.js'
import './assets/js/stats.js'
import './assets/js/island.js'
